git_common: &git_common
  github_owner: yourcompany
  github_app_name: aleph
  github_repo: aleph_queries
  auth_type: database

development:
  <<: *git_common
  github_ref: heads/development
  s3_bucket: aleph-development
  s3_folder: results
  auth_type: disabled

test:
  <<: *git_common
  auth_type: disabled

staging:
  <<: *git_common
  github_ref: heads/staging
  s3_bucket: aleph-staging
  s3_folder: results
  auth_type: database

production:
  <<: *git_common
  github_ref: heads/production
  s3_bucket: aleph-production
  s3_folder: results
  auth_type: database
